version: '3.8'
services:
  app:
    build: .
    ports:
      - "8443:8443"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mck
      - SPRING_DATASOURCE_USERNAME=demouser
      - SPRING_DATASOURCE_PASSWORD=J1uli.24
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mck
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=J1uli.24
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demouser -d mck"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
