   version: '3.8'
   services:
     postgres:
       image: postgres:13
       environment:
         POSTGRES_DB: demodb
         POSTGRES_USER: demouser
         POSTGRES_PASSWORD: demopass
       ports:
         - "5432:5432"
       volumes:
         - postgres_data:/var/lib/postgresql/data

   volumes:
     postgres_data: